version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet

  web:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - appnet

volumes:
  dbdata:

networks:
  appnet:

